name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git \
            bc \
            bison \
            build-essential \
            ccache \
            curl \
            flex \
            gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabi \
            libssl-dev \
            libelf-dev \
            zip \
            unzip \
            python3

      - name: Download Zyc Clang
        run: |
          git clone --depth=1 https://github.com/ZyCromerZ/Clang clang
          echo "$GITHUB_WORKSPACE/clang/bin" >> $GITHUB_PATH

      - name: Check clang
        run: |
          clang --version

      - name: Create output directory
        run: |
          sudo mkdir -p /mnt/d/users/juan/kernels/psyche
          sudo chmod -R 777 /mnt/d

      - name: Build Kernel
        run: |
          chmod +x build.sh
          bash build.sh psyche ksu
